name: OTP CI Build
# On [push, pull_request] causes double-builds when creating PRs.
# But triggering on push only will miss pull requests from outside authors.
# The push event's ref is the name of the pushed branch;
# The pull_request event's branch name is the merge target branch.
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v4
        with:
          repository: opentripplanner/OpenTripPlanner
          fetch-depth: 0

      # nodejs is needed because the dynamic download of it via the prettier maven plugin often
      # times out
      # Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4490450225/jobs/7897533439
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Java setup step completes very fast, no need to run in a preconfigured docker container
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Prepare coverage agent, build and test
        # these are split into two steps because otherwise maven keeps long-running HTTP connections
        # to Maven Central open which then hang during the package phase because the Azure (Github Actions)
        # NAT drops them
        # https://github.com/actions/runner-images/issues/1499
        # we set nodePath and npmPath to skip downloading the node binary, which frequently times out
        run: |
          mvn --batch-mode package -Dmaven.test.skip -P prettierSkip

      - run: echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          tag: ${{ env.RELEASE_TAG }}
